name: Flyway Migrations

on:
  push:
    branches: ["main"]

jobs:
  run-flyway:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download & Extract Flyway
        shell: powershell
        run: |
          $FlywayVersion = "9.20.0"
          $DownloadUrl = "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/$FlywayVersion/flyway-commandline-$FlywayVersion-windows-x64.zip"
          Invoke-WebRequest -Uri $DownloadUrl -OutFile flyway.zip
          Expand-Archive -Path flyway.zip -DestinationPath .\flyway
          $FlywayDir = (Get-ChildItem -Directory .\flyway | Select-Object -First 1).FullName
          "$FlywayDir" | Out-File -Append $Env:GITHUB_PATH

      - name: Set environment variables
        shell: powershell
        run: |
          $env:DB_URL = "${{ secrets.DB_URL }}"
          $env:DB_USER = "${{ secrets.DB_USER }}"
          $env:DB_PASSWORD = "${{ secrets.DB_PASSWORD }}"
          Write-Host "Environment variables set."

      - name: Run the flyway-automation script
        shell: pwsh
        run: .\scripts\flyway-automation.ps1
