name: Flyway Migrations

on:
  push:
    branches: [ "main" ]

jobs:
  run-flyway:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download & Extract Flyway (Java 17)
        shell: powershell
        run: |
          $FlywayVersion = "9.20.0"
          $DownloadUrl = "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/$FlywayVersion/flyway-commandline-$FlywayVersion-windows-x64.zip"
          Write-Host "Downloading Flyway $FlywayVersion..."
          Invoke-WebRequest -Uri $DownloadUrl -OutFile flyway.zip
          Expand-Archive -Path flyway.zip -DestinationPath .\flyway
          $FlywayDir = ".\flyway\flyway-commandline-$FlywayVersion-windows-x64"
          $env:PATH += ";$((Get-Location).Path)\$FlywayDir"

      - name: Run PowerShell automation script
        shell: pwsh
        run: |
          .\scripts\flyway-automation.ps1
